language: php
php:
    - "7.2"

cache:
    directories:
        - vendor

install:
    - composer install

script:
    - ./vendor/bin/phpcs -p
    - php bin/phpunit

after_success:
    - travis_retry php vendor/bin/php-coveralls -v
